### ISSUE TITLE
i have the mac version for the mini audio 

### ISSUE THREAD

**Issue by JonnycatMeow** [doggy-dentures/3dsenpai#2]
either invite me or allow file drops or changes

**Comment by JonnycatMeow** [comment]
cause i have the .a files ready

**Comment by doggy-dentures** [comment]
You can make a pull request with the .a files placed in the source/ma/lib folder.

**Comment by JonnycatMeow** [comment]
oh ok

**Comment by JonnycatMeow** [comment]
it says uploads are disable

**Comment by doggy-dentures** [comment]
Are you trying to fork+pull request, or are you trying to push your own commits into this repo?

**Comment by JonnycatMeow** [comment]
just pull request

**Comment by doggy-dentures** [comment]
You will need to fork this repo and then make your changes in the fork in order for a pull request to be available.

**Comment by JonnycatMeow** [comment]
bruh thats stupid

**Comment by JonnycatMeow** [comment]
@doggy-dentures merge it rn

**Comment by doggy-dentures** [comment]
👍
